version: '3.8'

services:
  mongo:
    container_name: renec-mongo
    image: mongo:4.4.18
    ports:
      - '27018:27017'
    volumes:
      - .docker/mongo/data:/data/db
      - .docker/mongo/backup:/data/backup
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: sample_db
      MONGODB_USER: renec
      MONGODB_PASS: renec123
      MONGODB_DATABASE: sample_db
    networks:
      - renec-network
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo db:27017/speech-api --quiet
      interval: 30s
      timeout: 10s
      retries: 5

# Docker Networks
networks:
  renec-network:
    name: renec-network
    driver: bridge

# Docker Volumes
volumes:
  .docker:
