version: '3.8'

services:
  api:
    container_name: renec-api
    build:
      context: ./apps/renec-api
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27018
      - MONGO_USER=renec
      - MONGO_PASS=renec123
      - MONGO_DB=sample_db
    ports:
      - '9010:9010'
    restart: always
    networks:
      - renec-network

  web:
    container_name: renec-web
    build:
      context: ./apps/renec-web
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - api
    environment:
      - API_HOST=http://api:9010
    ports:
      - '9020:3000'
    restart: always
    networks:
      - renec-network

  mongo:
    container_name: renec-mongo
    image: mongo:4.4.18
    ports:
      - '27018:27017'
    volumes:
      - .docker/mongo/data:/data/db
      - .docker/mongo/backup:/data/backup
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: sample_db
      MONGODB_USER: renec
      MONGODB_PASS: renec123
      MONGODB_DATABASE: sample_db
    networks:
      - renec-network
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo db:27017/speech-api --quiet
      interval: 30s
      timeout: 10s
      retries: 5 

# Docker Networks
networks:
  renec-network:
    name: renec-network
    driver: bridge

# Docker Volumes
volumes:
  .docker:
